import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/app/fonts";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Cloutera",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <div id="modal"></div>
        {children}
      </body>
    </html>
  );
}
