import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Cloutera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <div id="modal"></div>
        <div id="sidebar"></div>
        {children}
      </body>
    </html>
  );
}
